#!/bin/bash
declare -r RELATIVE_PATH_TO_ROOT=../..

# deletes all files and directories associated with the given trading strategies

# enter a list of strategies by their names as arguement to the script 
deleteStrategyDirectories(){
	local strategy_name=$1

	local STRATEGIES_DIR=$RELATIVE_PATH_TO_ROOT/R/TradingStrategies/$strategy_name
	local TESTS_DIR=$RELATIVE_PATH_TO_ROOT/R/ImplementedTests/TradingStrategies/$strategy_name
	local DOC_DIR=$RELATIVE_PATH_TO_ROOT/Doc/TradingStrategies/$strategy_name
	local TODO_DIR=$RELATIVE_PATH_TO_ROOT/ToDo/TradingStrategies/$strategy_name
	local PREVIOUSITERATIONS_DIR=$RELATIVE_PATH_TO_ROOT/PreviousIterations/TradingStrategies/$strategy_name

	if [ -d	$STRATEGIES_DIR ] || [ -d $TESTS_DIR ] || [ -d $DOC_DIR ] || [ -d $TODO_DIR ] || [ -d $PREVIOUSITERATIONS_DIR ]
	then
		rm -r $STRATEGIES_DIR
		rm -r $TESTS_DIR
		rm -r $DOC_DIR
		rm -r $TODO_DIR
		rm -r $PREVIOUSITERATIONS_DIR

	echo "Success: Strategy directories for '"$strategy_name"' have been deleted"

	else
		echo "Failure: Cannot Delete Strategy: Strategy with name '"$strategy_name"' does not exist"
	fi
}

for strategy_name in $@; do
	deleteStrategyDirectories $strategy_name
done
